[![Build Status](https://dev.azure.com/yehuditZ/yehuditz/_apis/build/status/yehuditz.yehudit-zaritzky?branchName=master)](https://dev.azure.com/yehuditZ/yehuditz/_build/latest?definitionId=1&branchName=master)
# Starter pipeline


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
